### ISSUE TITLE
Palette gieve

### ISSUE THREAD

**Issue by cristiangrossano** [myNicole98/Xournalpp-Catppuccin#1]
![swappy-20231229_125506](https://github.com/myNicole98/Xournalpp-Catppuccin/assets/81424772/edadab69-f6d5-4ccd-8b4f-ab29633176e0)

**Comment by myNicole98** [comment]
Hi,
would you mind telling me which Xournal++ version you're using and the flavour you wanted to apply?

Edit: Nevermind. I've found what was causing this issue. For some reasons it doesn't parse correctly if there isn't an empty line at the end of the gpl file. Fixed in commit [03885c3](https://github.com/myNicole98/Xournalpp-Catppuccin/commit/03885c31f6bd2e7ac7ceb7ccc9b55c1dd442f074)

If it still happens feel free to reopen the issue (and check if there's an empty line at the end of your palette file)
